### ISSUE TITLE
微信小程序wx.openDocument  在android手机上没有问题，每次都能打开，但是ios手机上出现频繁，只能偶尔打开

### ISSUE THREAD

**Issue by Hyupeng1006** [mcya/JavaScriptExperience#49]
每次都能进入成功回调，但就是文件不出来，android手机上没有问题，每次都能打开，但是ios手机上出现频繁，只能偶尔打开。求大神帮助！

**Comment by mcya** [comment]
[微信小程序 归类](https://github.com/mcya/JavaScriptExperience/issues/39)
